source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView


app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/hello/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('photo/', include([
        path('<int:pk>/', include([
            path('', PhotoView.as_view(), name='photo_view'),
            path('update/', PhotoUpdateView.as_view(), name='photo_update'),
            path('delete/', PhotoDeleteView.as_view(), name='photo_delete'),
            path('comments/add/', PhotoCommentCreateView.as_view(),
                 name='photo_comment_add'),
            path('chose/', PhotoLikeView.as_view(), name='photo_chosen'),
            path('not_chosed/', PhotoNotChosenView.as_view(), name='photo_not_chosen'),
        ])),
        path('add/', PhotoCreateView.as_view(), name='photo_create'),
    ])),

    path('comment/', include([
        path('<int:pk>/', include([
            path('update/', CommentUpdateView.as_view(), name='comment_update'),
            path('delete/', CommentDeleteView.as_view(), name='comment_delete'),
        ]))
    ]))
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Photo(models.Model):
    image = models.ImageField(null=False, blank=False, upload_to='pics', verbose_name='Фотография')
    description = models.TextField(null=False, blank=False, max_length=2000, verbose_name='Подпись')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    author_name = models.CharField(null=False, blank=False, max_length=50, verbose_name='Автор')

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'


class Comment(models.Model):
    photo = models.ForeignKey('webapp.Photo', related_name='comments', on_delete=models.CASCADE, verbose_name='Фото')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1,
                               related_name='comments', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Chosen(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='chosen',
                             verbose_name='Пользователь')
    photo = models.ForeignKey('webapp.Photo', on_delete=models.CASCADE, related_name='likes', verbose_name='Статья')

    def __str__(self):
        return f'{self.user.name} - {self.photo.image}'

    class Meta:
        verbose_name = 'Избраные'
        verbose_name_plural = 'Избраные'

source/webapp/forms.py
from django import forms
from django.core.validators import BaseValidator
from django.utils.deconstruct import deconstructible

from webapp.models import Photo, Comment


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'description', 'author_name']


class XDatepickerWidget(forms.TextInput):
    template_name = 'widgets/xdatepicker_widget.html'


@deconstructible
class MinLengthValidator(BaseValidator):
    message = 'Value "%(value)s" has length of %(show_value)d! It should be at least %(limit_value)d symbols long!'
    code = 'too_short'

    def compare(self, value, limit):
        return value < limit

    def clean(self, value):
        return len(value)


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class PhotoCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

source/webapp/views/base_views.py
from django.db.models import Q
from django.views.generic import View, TemplateView, \
    ListView as DjangoListView
from django.shortcuts import render, redirect, get_object_or_404

from webapp.forms import SimpleSearchForm


class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_context_data(self, **kwargs):
        return kwargs

    def get_redirect_url(self):
        return self.redirect_url


class ListView(TemplateView):
    model = None
    context_key = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_queryset()
        return context

    def get_queryset(self):
        return self.model.objects.all()


class DetailView(TemplateView):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


class CreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return self.redirect_url


class SearchView(DjangoListView):
    search_form_class = SimpleSearchForm
    search_form_field = 'search'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value(self.search_form)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = self.search_form
        context['search_value'] = self.search_value
        return context

    def get_queryset(self):
        data = super().get_queryset()
        query = self.get_query(self.search_value)
        data = data.filter(query)
        return data

    def get_search_form(self):
        return self.search_form_class(data=self.request.GET)

    def get_search_value(self, form):
        search_value = None
        if form.is_valid():
            search_value = form.cleaned_data.get(self.search_form_field, None)
        return search_value

    def get_query(self, search_value):
        query = Q()
        if search_value:
            for field in self.search_fields:
                kwargs = {field: search_value}
                query = query | Q(**kwargs)
        return query


class UpdateView(View):
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    key_kwarg = 'pk'
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form(self):
        form_kwargs = self.get_form_kwargs()
        form = self.form_class(**form_kwargs)
        return form

    def get_form_kwargs(self):
        kwargs = {'instance': self.object}
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_context_data(self, **kwargs):
        context = self.kwargs.copy()
        context[self.context_key] = self.object
        context.update(kwargs)
        return context

    def get_redirect_url(self):
        return self.redirect_url


class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.models import Comment, Photo
from webapp.forms import PhotoCommentForm


class PhotoCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comment/comment_create.html'
    form_class = PhotoCommentForm

    def form_valid(self, form):
        photo = get_object_or_404(Photo, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.photo = photo
        comment.author = self.request.user
        comment.save()
        # form.save_m2m()  ## для сохранения связей многие-ко-многим
        return redirect('webapp:photo_view', pk=photo.pk)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/comment_update.html'
    form_class = PhotoCommentForm
    permission_required = 'webapp.change_comment'

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.photo.pk})


class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.photo.pk})

source/webapp/views/photo_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View

from webapp.models import Photo, Chosen


class IndexView(ListView):
    template_name = 'photo/index.html'
    context_object_name = 'photos'
    model = Photo
    ordering = '-creation_date'


class PhotoView(DetailView):
    template_name = 'photo/photo_view.html'
    pk_url_kwarg = 'pk'
    model = Photo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = context['photo'].comments.order_by('-created_at')
        self.paginate_comments_to_context(comments, context)
        context['user'] = self.request.user
        return context

    def paginate_comments_to_context(self, comments, context):
        paginator = Paginator(comments, 10, 0)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['comments'] = page.object_list
        context['is_paginated'] = page.has_other_pages()


class PhotoCreateView(CreateView):
    template_name = 'photo/photo_create.html'
    model = Photo
    fields = ['image', 'description']

    def form_valid(self, form):
        form.instance.author_name = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:index')


class PhotoUpdateView(UpdateView):
    model = Photo
    template_name = 'photo/photo_update.html'
    fields = ['image', 'description', 'author_name']
    context_object_name = 'obj'

    def get_success_url(self):
        return reverse('webapp:index')


class PhotoDeleteView(DeleteView):
    template_name = 'photo/photo_delete.html'
    model = Photo
    context_object_name = 'obj'
    success_url = reverse_lazy('webapp:index')


class PhotoLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs.get('pk'))
        chosen, created = Chosen.objects.get_or_create(photo=photo, user=request.user)
        if created:
            photo.chosen_count += 1
            photo.save()
            return HttpResponse(photo.chosen_count)
        else:
            return HttpResponseForbidden()


class PhotoNotChosenView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs.get('pk'))
        chosen = get_object_or_404(photo.chosens, user=request.user)
        chosen.delete()
        photo.chosen_count -= 1
        photo.save()
        return HttpResponse(photo.chosen_count)

source/webapp/templates/partial/form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}" id="{{ form_id }}">
        {% csrf_token %}
{% endif %}

        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            {% include 'partial/form_field.html' %}
        {% endfor %}

{% if not fields_only %}
        <br/>
        <input type="submit" value="{{ button_text|default:"Submit" }}"/>
    </form>
{% endif %}

source/webapp/templates/partial/form_field.html
{% load widget_tweaks %}

<label for="{{ field.id_for_label }}">
    {% if field.field.required %}
        <span class="red">*</span>
    {% endif %}
    {{ field.label }}:
</label>
<br/>
{% if field|field_type == 'modelmultiplechoicefield' %}
    {{ field|add_class:'form-checkboxes'|add_error_class:'form-error' }}
{% else %}
    {{ field|add_class:'form-input'|add_error_class:'form-error' }}
{% endif %}
<br/>
{% for error in field.errors %}
    <p class="error">{{ error }}</p>
{% endfor %}
<br/>

source/webapp/templates/partial/pagination.html
{% load page_utils %}

<div class="pagination">
    <span class="step-links">
        <a href="?{{ request|page_query_string:1 }}">&laquo; В начало</a>

        {% if page_obj.has_previous %}
            <a href="?{{ request|page_query_string:page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}


        <form class="current-page" method="get">
            <label for="page">
                {% for key, value in request.GET.items %}
                    {% if not key == 'page' %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?{{ request|page_query_string:page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}

        <a href="?{{ request|page_query_string:page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

source/webapp/templates/partial/photo_list.html
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

{% if show_mass_delete %}
    <form action="{% url "webapp:photo_mass_action" %}" method="post">
        {% csrf_token %}
        <p class="mass-actions"><input type="submit" name="delete" value="Delete selected"></p>
{% endif %}
        {% for photo in photos %}
            <div class="box">
                <h3><a href="{% url "webapp:photo_view" photo.pk %}">{{ photo.title }}</a></h3>
                {% if show_mass_delete %}
                    <p>
                        <label for="selected_photos-{{ photo.pk }}">Select:</label>
                        <input type="checkbox" name="selected_photos"
                               id="selected_photos-{{ photo.pk }}" value="{{ photo.pk }}">
                    </p>
                {% endif %}
                <p>Статус: ({{ photo.status }} | {{ photo.get_status_display }})</p>
                <p>
                    <a href="{% url 'accounts:detail' photo.author_id %}">{{ photo.author }}</a>
                    | {{ photo.created_at|date:"d.m.Y H:i:s" }}
                </p>
                <p>Published at: {{ photo.publish_at|date:"d.m.Y H:i:s" }}</p>
                {% if perms.webapp.change_photo or photo.author == request.user %}
                    <p><a href="{% url 'webapp:photo_update' photo.pk %}">Update</a></p>
                {% endif %}
                {% if perms.webapp.delete_photo or photo.author == request.user %}
                    <p><a href="{% url 'webapp:photo_delete' photo.pk %}">Delete</a></p>
                {% endif %}
                {% if user.is_authenticated %}
                    <p>
                        <span class="counter">{{ photo.like_count }}</span>
                        {% with photo|chosed_by:user as chosed %}
                            <a class="{% if chosed %}hidden{% endif %} chose" href="{% url 'webapp:photo_chose' photo.pk %}">В избраное</a>
                            <a class="{% if not chosed %}hidden{% endif %} not_chose" href="{% url 'webapp:photo_chose' photo.pk %}">Убрать</a>
                        {% endwith %}
                    </p>
                {% endif %}
            </div>
        {% empty %}
            <h2 class="text-center">Нет статей</h2>
        {% endfor %}
{% if show_mass_delete %}
    </form>
{% endif %}

{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}